# Generated by Django 6.0.3 on 2026-04-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_alter_product_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payoutnotification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payoutnotification',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='RateCache',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PayoutNotification',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
