# Generated by Django 6.0.3 on 2026-04-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('rates', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
                ('stale', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rate Cache',
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
